Add Item Show Page
Middlebrooks314/react-guilded-rose-llc pull request #5
Opened 2021-05-11 20:21 UTC by Middlebrooks314

**Summary** 

The `add-item-show-page` branch adds the user's ability to click on any item from the items table. When the user clicks on an item link, they will be taken to the item show page where all of the item details are displayed. 

When I implemented the new feature I shifted to a functional react implementation in order to support react router. Aside from the apiHandler, all of the components are now functional components. 

https://user-images.githubusercontent.com/43938783/117878755-b3a34a80-b26b-11eb-89db-01140860765f.mov

2021-05-11 20:38 UTC, cmvandrevala requested changes

2021-05-11 20:38 UTC, cmvandrevala commented on src/apiHandler.js
> +    const { data, error } = useFetch("https://safe-wave-09726.herokuapp.com/api/v1/welcome", {
Request for Change: You defined `apiURL` on line 2, but did not use it here.

2021-05-11 20:38 UTC, cmvandrevala commented on src/apiHandler.js
> +    const { data, error } = useFetch("https://floating-spire-59497.herokuapp.com/api/v1/items", {
Request for Change: You have two different URLs - `floating-spire` and `safe-wave`. Do they point to different environments?

Remember you want the code to use the right URL in each environment, so you may have to inject that value in when you start the app.

2021-05-11 20:38 UTC, cmvandrevala commented on src/components/itemPage/itemPage.js
> +      <>
Question: Do you need the fragment here? Can you just return the tags without the fragment?

2021-05-11 20:38 UTC, cmvandrevala commented on src/components/itemPage/itemPage.test.js
> +      screen.getByText("Item: Bar"),
Comment, No Change Required: The tests for `getByTestId` are good because you can change the wording and the tests are not going to change. The ones with `getByText` are not as stable because when the wording on the frontend changes (which happens pretty often, to be honest), those tests will break.

Having one or two tests for text is not a terrible thing in specific cases, but keep in mind those are brittle tests

2021-05-11 20:38 UTC, cmvandrevala commented on src/components/itemsIndex/itemsIndex.js
> +      const errorMessage = <h5 data-testid="no-items-message">No items available</h5>
Praise: Nice default

2021-05-11 20:38 UTC, cmvandrevala commented on src/components/welcome/welcome.js
> +
Request for Change: Extra whitespace

2021-05-11 20:55 UTC, Middlebrooks314 commented on src/components/itemPage/itemPage.js
> +      <>
Yes, they need a parent element. 

`SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (11:8)`

2021-05-13 01:06 UTC, cmvandrevala approved these changes

2021-05-13 01:19 UTC, merged